os: Visual Studio 2015

build_script:
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet --verbose build "src\ReadingTimeDemo"
  - ps: dotnet test "test\ReadingTimeDemo.UnitTests"
  - runcoverage.ps1

test: off 