# /usr/local/bin/docker-compose
# docker-compose run --rm test
version: '3'
services:
  test:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["sh", "./build.sh"]