name: Build test and deploy review app

on: pull_request

jobs:

  build:
    env: 
      RESOURCE_GROUP: ${{ github.actor }}-readingtimedemo-grp

    runs-on: ubuntu-latest   
    steps:
    
    - uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Login to Azure
      uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Build and test
      run: |
        dotnet build --configuration Release
        dotnet test test/ReadingTimeDemo.UnitTests --configuration Release
        dotnet publish src/ReadingTimeDemo --configuration Release -o ReadingTimeDemo --no-build --no-restore

    - name: Create deployment
      run: echo "TODO Create deployment"
        
    - name: Deploy
      id: azure
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{ github.actor }}-readingtimedemo-app
        package: './src/ReadingTimeDemo/ReadingTimeDemo' 
 
    - name: Update GitHub deployment status to success
      run: echo "Update GitHub deployment status to success"
      env:
        WEB_APP: ${{ steps.azure.outputs.webapp-url }}

    - name: Update GitHub deployment status to failure
      if: failure()
      run: echo "Update GitHub deployment status to failure"
   
    - name: logout
      run: az logout
